[env:esp32dev]
platform = espressif32
board = nodemcu-32s
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L
upload_speed = 115200
lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    adafruit/Adafruit MPU6050@^2.2.6
    adafruit/Adafruit Unified Sensor@^1.1.14
