[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
  C:/Users/deban/OneDrive/Documents/GitHub/PRISM-Psychological-Risk-Insight-Signal-Monitoring/prism_edge/prism_pulse/.pio/libdeps/esp32dev/LiquidCrystal_I2C
  C:/Users/deban/OneDrive/Documents/GitHub/PRISM-Psychological-Risk-Insight-Signal-Monitoring/prism_edge/prism_pulse/.pio/libdeps/esp32dev/Adafruit MPU6050
  C:/Users/deban/OneDrive/Documents/GitHub/PRISM-Psychological-Risk-Insight-Signal-Monitoring/prism_edge/prism_pulse/.pio/libdeps/esp32dev/Adafruit Unified Sensor
